package:
  name: "demopackage"
  version: "0.1"

source:
  git_rev: "0.1.2"
  git_url: https://github.com/twicki/conda_upload

build:
  number: "0"
  script: "{{ PYTHON }} -m pip install ./demopackage "

requirements:
  host:
    - python>=3.10
    - pip>=22.3
    - cartopy
    - matplotlib
  run:
    - python>=3.10
    - pip>=22.3
    - cartopy
    - matplotlib

test:
  imports:
    - demopackage

